import type { Exercise, Food, Plan } from "./types";

export const EXERCISES: Exercise[] = [
  {
    id: "squat",
    name: "Приседания",
    muscles: ["квадрицепс", "ягодицы"],
    regions: ["legs", "glutes"],
    equipment: [],
    jumps: false,
    sets: 3,
    reps: 12,
    unit: "rep",
    restSec: 45,
    cues: ["Колени следят за носками", "Таз назад, грудь открыта", "Пятки в полу"],
    poster: "/exercises/squat.svg",
    video: "/exercises/squat.mp4",
  },
  {
    id: "pushup",
    name: "Отжимания",
    muscles: ["грудь", "трицепс"],
    regions: ["chest", "arms", "shoulders"],
    equipment: [],
    jumps: false,
    sets: 3,
    reps: 8,
    unit: "rep",
    restSec: 50,
    cues: ["Корпус прямой", "Локти ~45°", "Не проваливай поясницу"],
    poster: "/exercises/pushup.svg",
    video: "/exercises/pushup.mp4",
  },
  {
    id: "glute-bridge",
    name: "Ягодичный мост",
    muscles: ["ягодицы", "задняя поверхность"],
    regions: ["glutes", "legs"],
    equipment: [],
    jumps: false,
    sets: 3,
    reps: 15,
    unit: "rep",
    restSec: 40,
    cues: ["Дави пятками", "Сжимай ягодицы вверху", "Не переразгибай поясницу"],
    poster: "/exercises/glute-bridge.svg",
    video: "/exercises/glute-bridge.mp4",
  },
  {
    id: "plank",
    name: "Планка",
    muscles: ["кор", "плечи"],
    regions: ["core", "shoulders"],
    equipment: [],
    jumps: false,
    sets: 3,
    reps: 40,
    unit: "sec",
    restSec: 40,
    cues: ["Локти под плечами", "Таз не провисает", "Дыши ровно"],
    poster: "/exercises/plank.svg",
    video: "/exercises/plank.mp4",
  },
  {
    id: "row-band",
    name: "Тяга резинки",
    muscles: ["спина", "бицепс"],
    regions: ["back", "arms"],
    equipment: ["bands"],
    jumps: false,
    sets: 3,
    reps: 12,
    unit: "rep",
    restSec: 45,
    cues: ["Лопатки своди", "Локти вдоль корпуса", "Не сутулься"],
    poster: "/exercises/row-band.svg",
    video: "/exercises/row-band.mp4",
  },
  {
    id: "lunge",
    name: "Выпады",
    muscles: ["квадрицепс", "ягодицы"],
    regions: ["legs", "glutes"],
    equipment: [],
    jumps: false,
    sets: 3,
    reps: 10,
    unit: "rep",
    restSec: 50,
    cues: ["Шаг не слишком широкий", "Колено над стопой", "Корпус вертикально"],
    poster: "/exercises/lunge.svg",
    video: "/exercises/lunge.mp4",
  },
  {
    id: "shoulder-press",
    name: "Жим гантелей стоя",
    muscles: ["плечи", "трицепс"],
    regions: ["shoulders", "arms"],
    equipment: ["dumbbells"],
    jumps: false,
    sets: 3,
    reps: 10,
    unit: "rep",
    restSec: 50,
    cues: ["Не прогибай поясницу", "Локти чуть вперёд", "Контролируй опускание"],
    poster: "/exercises/shoulder-press.svg",
    video: "/exercises/shoulder-press.mp4",
  },
  {
    id: "dead-bug",
    name: "Dead bug",
    muscles: ["кор"],
    regions: ["core"],
    equipment: [],
    jumps: false,
    sets: 3,
    reps: 10,
    unit: "rep",
    restSec: 35,
    cues: ["Поясница прижата", "Двигай противоположные конечности", "Медленно"],
    poster: "/exercises/dead-bug.svg",
    video: "/exercises/dead-bug.mp4",
  },
  {
    id: "pullup",
    name: "Подтягивания",
    muscles: ["спина", "бицепс"],
    regions: ["back", "arms"],
    equipment: ["pullup"],
    jumps: false,
    sets: 3,
    reps: 6,
    unit: "rep",
    restSec: 70,
    cues: ["Лопатки вниз", "Подбородок выше перекладины", "Без рывков"],
    poster: "/exercises/pullup.svg",
    video: "/exercises/pullup.mp4",
  },
  {
    id: "chair-dip",
    name: "Отжимания от стула",
    muscles: ["трицепс", "грудь"],
    regions: ["arms", "chest"],
    equipment: ["chair"],
    jumps: false,
    sets: 3,
    reps: 10,
    unit: "rep",
    restSec: 45,
    cues: ["Локти назад", "Плечи опущены", "Не уходи слишком низко"],
    poster: "/exercises/chair-dip.svg",
    video: "/exercises/chair-dip.mp4",
  },
  {
    id: "side-plank",
    name: "Боковая планка",
    muscles: ["кор", "косые"],
    regions: ["core"],
    equipment: [],
    jumps: false,
    sets: 2,
    reps: 30,
    unit: "sec",
    restSec: 30,
    cues: ["Тело в одной линии", "Таз не провисает", "Дыши"],
    poster: "/exercises/side-plank.svg",
    video: "/exercises/side-plank.mp4",
  },
  {
    id: "hip-thrust",
    name: "Hip thrust",
    muscles: ["ягодицы"],
    regions: ["glutes"],
    equipment: [],
    jumps: false,
    sets: 3,
    reps: 12,
    unit: "rep",
    restSec: 45,
    cues: ["Подбородок к груди", "Выталкивай таз вверх", "Пауза вверху"],
    poster: "/exercises/hip-thrust.svg",
    video: "/exercises/hip-thrust.mp4",
  },
];

export const PLANS: Plan[] = [
  {
    id: "full-15",
    title: "Всё тело · 15 мин",
    minutes: 15,
    focus: "Общий тонус",
    muscles: ["ноги", "кор", "грудь"],
    jumps: false,
    exerciseIds: ["squat", "pushup", "glute-bridge", "plank"],
    goals: ["tone", "energy"],
  },
  {
    id: "legs-25",
    title: "Ноги и ягодицы · 25 мин",
    minutes: 25,
    focus: "Низ тела",
    muscles: ["ноги", "ягодицы"],
    jumps: false,
    exerciseIds: ["squat", "lunge", "glute-bridge", "hip-thrust", "plank"],
    goals: ["tone", "strength"],
  },
  {
    id: "upper-25",
    title: "Верх тела · 25 мин",
    minutes: 25,
    focus: "Сила верха",
    muscles: ["грудь", "спина", "плечи"],
    jumps: false,
    exerciseIds: ["pushup", "row-band", "shoulder-press", "chair-dip", "plank"],
    goals: ["strength", "tone"],
  },
  {
    id: "core-15",
    title: "Кор · 15 мин",
    minutes: 15,
    focus: "Стабильность",
    muscles: ["кор"],
    jumps: false,
    exerciseIds: ["plank", "dead-bug", "side-plank", "glute-bridge"],
    goals: ["energy", "recovery"],
  },
  {
    id: "full-40",
    title: "Полная · 40 мин",
    minutes: 40,
    focus: "Сила и объём",
    muscles: ["всё тело"],
    jumps: false,
    exerciseIds: [
      "squat",
      "pushup",
      "row-band",
      "lunge",
      "shoulder-press",
      "hip-thrust",
      "plank",
      "dead-bug",
    ],
    goals: ["strength", "tone"],
  },
  {
    id: "recovery-15",
    title: "Мягко · 15 мин",
    minutes: 15,
    focus: "Восстановление",
    muscles: ["кор", "ягодицы"],
    jumps: false,
    exerciseIds: ["glute-bridge", "dead-bug", "side-plank"],
    goals: ["recovery", "energy"],
    optional: true,
  },
];

export const FOODS: Food[] = [
  { id: "oats", name: "Овсянка", kcal: 370, protein: 13, fat: 7, carbs: 60 },
  { id: "egg", name: "Яйцо", kcal: 155, protein: 13, fat: 11, carbs: 1 },
  { id: "chicken", name: "Куриная грудка", kcal: 165, protein: 31, fat: 3.6, carbs: 0 },
  { id: "rice", name: "Рис варёный", kcal: 130, protein: 2.7, fat: 0.3, carbs: 28 },
  { id: "cottage", name: "Творог 5%", kcal: 121, protein: 17, fat: 5, carbs: 3 },
  { id: "banana", name: "Банан", kcal: 89, protein: 1.1, fat: 0.3, carbs: 23 },
  { id: "yogurt", name: "Йогурт греческий", kcal: 97, protein: 9, fat: 5, carbs: 3.6 },
  { id: "salmon", name: "Лосось", kcal: 208, protein: 20, fat: 13, carbs: 0 },
  { id: "broccoli", name: "Брокколи", kcal: 34, protein: 2.8, fat: 0.4, carbs: 7 },
  { id: "almonds", name: "Миндаль", kcal: 579, protein: 21, fat: 50, carbs: 22 },
  { id: "bread", name: "Хлеб цельнозерновой", kcal: 247, protein: 13, fat: 4, carbs: 41 },
  { id: "apple", name: "Яблоко", kcal: 52, protein: 0.3, fat: 0.2, carbs: 14 },
];

export function exerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}

export function planById(id: string): Plan | undefined {
  return PLANS.find((p) => p.id === id);
}

export function foodById(id: string): Food | undefined {
  return FOODS.find((f) => f.id === id);
}

export function planExercises(plan: Plan): Exercise[] {
  return plan.exerciseIds.map((id) => exerciseById(id)).filter(Boolean) as Exercise[];
}
